config/routes.rb
Sisdun::Application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  resources :categories
  resources :products
  resources :companies
  resources :customers
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/cities_by_state', to: 'companies#cities_by_state', via: 'get'
  match '/cities_by_state', to: 'customers#cities_by_state', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <hr>
    <span>
    <a href="https://github.com/WanderleyJunior/sisdun">SISDUN Projeto Github</a>
    by Wanderley Junior
    </span>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fluid-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="brand" href="#">Sisdun</a>
            <div class="container-fluid">
              <ul class="nav pull-right">
                <li><%= link_to "Home", root_path %></li>
                <% if signed_in? %>
                  <li id="fat-menu" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <%= current_user.name %> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Configurações", edit_user_path(current_user) %></li>
                      <% if current_user.admin? %>
                        <li class="divider"></li>
                        <li><%= link_to "Usuários", users_path %></li>
                      <% end %>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Sair", signout_path, method: :delete %>
                      </li>
                    </ul>
                  </li>
            <% else %>
              <li><%= link_to "Entrar", signin_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Navegação</li>
      <% if signed_in? %> 
        <li><%= link_to "Pedidos", '#' %></li>
        <li><%= link_to "Clientes", customers_path %></li>
        <li><%= link_to "Empresas", companies_path %></li>
        <li><%= link_to "Produtos", products_path %></li>
        <li><%= link_to "Categorias", categories_path %></li>
        <% if current_user.admin? %>
          <li class="divider"></li>
          <li class="nav-header">Administração</li>
          <li><%= link_to "Usuários", users_path %></li>
        <% end %>
      <% else %>
        <li><%= link_to "Entrar", signin_path %></li>
      <% end %>
    </ul>
  </div><!--/.well -->

app/views/layouts/_sidebar_cart.html.erb
<div class="well sidebar-nav">
<%= link_to 'Catalogo de Produtos', store_index_path %>
<div id="cart">
      <%= render @cart %>
</div>
</div><!--/.well -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all",
                                              "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">

          <% if signed_in? %>
            <%= render 'layouts/sidebar_cart' %>
          <% end %>
          <%= render 'layouts/sidebar' %>
        </div>
        <div class="span9">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>" data-alert='alert'>
              <a class="close" data-dismiss='alert' href="#">×</a>
              <%= value %>
            </div>
          <% end %>
          <%= yield %>
          <br/><br/><%= debug(params) if Rails.env.development? %>
        </div>
      </div><!--/row-->
      <%= render 'layouts/footer' %>
  </body>
</html>